name: wave_app
description: "Application de transfert d'argent Wave..."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter_secure_storage: ^8.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0
  mime: ^1.0.0
  
  # Contact handling
  flutter_contacts: ^1.1.7+1
  provider: ^6.0.5
  http: ^1.1.0
          
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # Networking
  dio: ^5.4.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Image Handling
  #image_picker: ^1.0.7
  path: ^1.9.0
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  
  # Formatting
  intl: ^0.19.0  # Mis à jour pour utiliser 0.19.0 comme requis par flutter_localizations

dev_dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^10.0.0 # Pour gérer les autorisations

dependency_overrides:
  intl: ^0.19.0  # Force la version d'intl à 0.19.0 pour tous les packages

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/samaxaalis.jpeg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/samaxaalis.jpeg    
    - assets/images/logo_wave.png
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
